-- Generated by Galactic decompiler .gg/qy2neXET6W

local v1_1 = game:GetService("CoreGui")
local v2_1 = v1_1:FindFirstChild("VylikUI")

if not v2_1 then
end

local v5_1 = Instance.new("ScreenGui")
v5_1.Name = "VylikUI"
v5_1.ResetOnSpawn = false
v5_1.IgnoreGuiInset = true
v5_1.Parent = v1_1
local v6_1 = Instance.new("ImageLabel")
v6_1.Name = "Shadow"
local v7_1 = Vector2.new(0.5, 0.5)
v6_1.AnchorPoint = v7_1
v7_1 = UDim2.new(0, 285, 0, 350)
v6_1.Size = v7_1
v7_1 = UDim2.new(0.5, 0, 0.5, 28)
v6_1.Position = v7_1
v6_1.BackgroundTransparency = 1
v6_1.Image = "rbxassetid://136559706836779"
v6_1.ScaleType = Enum.ScaleType.Slice
v7_1 = Rect.new(60, 48, 64, 48)
v6_1.SliceCenter = v7_1
v6_1.SliceScale = 1.15
v7_1 = Color3.new(0, 0, 0)
v6_1.ImageColor3 = v7_1
v6_1.ZIndex = 0
v6_1.Parent = v5_1
v7_1 = Instance.new("Frame")
local v8_1 = UDim2.new(0, 210, 0, 275)
v7_1.Size = v8_1
v8_1 = UDim2.new(0.5, -105, 0.5, -110)
v7_1.Position = v8_1
v8_1 = Color3.new(0, 0, 0)
v7_1.BackgroundColor3 = v8_1
v7_1.BackgroundTransparency = 0
v7_1.BorderSizePixel = 0
v7_1.Active = true
v7_1.Draggable = false
v7_1.Name = "MainFrame"
v7_1.ZIndex = 1
v7_1.Parent = v5_1
v8_1 = Instance.new("UICorner", v7_1)
local v9_1 = UDim.new(0, 12)
v8_1.CornerRadius = v9_1
v9_1 = Instance.new("TextButton")
local v10_1 = UDim2.new(0, 120, 0, 35)
v9_1.Size = v10_1
v10_1 = UDim2.new(1, -190, 0, 8)
v9_1.Position = v10_1
v9_1.Text = "Hide GUI"
v9_1.Font = Enum.Font.Gotham
v9_1.TextSize = 22
v10_1 = Color3.fromRGB(25, 25, 25)
v9_1.BackgroundColor3 = v10_1
v10_1 = Color3.new(1, 1, 1)
v9_1.TextColor3 = v10_1
v9_1.Parent = v5_1
v10_1 = Instance.new("UICorner", v9_1)
local v11_1 = UDim.new(0, 8)
v10_1.CornerRadius = v11_1
v11_1 = Instance.new("TextButton")
local v12_1 = UDim2.new(0, 25, 0, 25)
v11_1.Size = v12_1
v12_1 = UDim2.new(1, -30, 0, 5)
v11_1.Position = v12_1
v11_1.Text = "��️"
v11_1.Font = Enum.Font.Gotham
v11_1.TextSize = 14
v12_1 = Color3.fromRGB(40, 40, 40)
v11_1.BackgroundColor3 = v12_1
v12_1 = Color3.new(1, 1, 1)
v11_1.TextColor3 = v12_1
v11_1.Parent = v7_1
v12_1 = Instance.new("UICorner", v11_1)
local v13_1 = UDim.new(0, 12)
v12_1.CornerRadius = v13_1

local v15_1 = function()
  upval_0:Destroy()
end

v11_1.MouseButton1Click:Connect(v15_1)

local v16_1 = function()
  upval_0 = not upval_0
  upval_1.Visible = not upval_0
  upval_2.Visible = not upval_0

  if upval_0 then
    local v1_17 = UDim2.new(0.5, -105, 0.5, -110)
    upval_1.Position = v1_17
    v1_17 = UDim2.new(0.5, 0, 0.5, 28)
    upval_2.Position = v1_17
  end

  if not upval_0 then
    if "Show GUI" then
    else
    end
  end
  upval_3.Text = "Hide GUI"
end

v9_1.MouseButton1Click:Connect(v16_1)
local v18_1 = game:GetService("UserInputService")

local v21_1 = function(G0_11)

  if v0_11.UserInputType ~= Enum.UserInputType.MouseButton1 then
    if v0_11.UserInputType == Enum.UserInputType.Touch then
    else
      upval_0 = true
      upval_1 = v0_11.Position
      upval_2 = upval_3.Position

      local v3_11 = function()
        if upval_0.UserInputState == Enum.UserInputState.End then
          upval_1 = false
        end
      end

      v0_11.Changed:Connect(v3_11)
    end
  end
end

v7_1.InputBegan:Connect(v21_1)

local v21_1 = function(G0_15)

  if v0_15.UserInputType ~= Enum.UserInputType.MouseMovement then
    if v0_15.UserInputType == Enum.UserInputType.Touch then
    else
      upval_0 = v0_15
    end
  end
end

v7_1.InputChanged:Connect(v21_1)

local v21_1 = function(G0_6)

  if v0_6 == upval_0 then
    if not upval_1 then
      local v3_6 = UDim2.new(upval_4.X.Scale, upval_4.X.Offset + v0_6.Position - upval_2.X, upval_4.Y.Scale, upval_4.Y.Offset + v0_6.Position - upval_2.Y)
      upval_3.Position = v3_6
      v3_6 = UDim2.new(0.5, upval_3.Position.X.Offset + 105, 0.5, upval_3.Position.Y.Offset + 138)
      upval_5.Position = v3_6
    end
  end
end

v18_1.InputChanged:Connect(v21_1)

local v19_1 = function(G0_2, G1_2)
  local v2_2 = Instance.new("TextButton")
  local v3_2 = UDim2.new(1, -20, 0, 30)
  v2_2.Size = v3_2
  v3_2 = UDim2.new(0, 10, 0.1, v1_2)
  v2_2.Position = v3_2
  v2_2.Text = v0_2
  v2_2.Font = Enum.Font.Gotham
  v2_2.TextSize = 14
  v3_2 = Color3.fromRGB(40, 40, 40)
  v2_2.BackgroundColor3 = v3_2
  v3_2 = Color3.new(1, 1, 1)
  v2_2.TextColor3 = v3_2
  v2_2.Parent = upval_0
  v3_2 = Instance.new("UICorner", v2_2)
  local v4_2 = UDim.new(0, 8)
  v3_2.CornerRadius = v4_2
  return v2_2
end

local v20_1 = v19_1("Get INF Coins\
+ Tools From Crate", 5)

local v23_1 = function()
  local v1_14 = game:GetService("ReplicatedStorage")
  v1_14 = v1_14:WaitForChild("CratesUtilities")
  v1_14 = v1_14:WaitForChild("Remotes")
  v1_14 = v1_14:WaitForChild("GiveReward")
  v1_14:FireServer(v1_14)
  local v2_14 = game:GetService("ReplicatedStorage")
  v2_14 = v2_14:WaitForChild("CratesUtilities")
  v2_14 = v2_14:WaitForChild("Remotes")
  v2_14 = v2_14:WaitForChild("GiveReward")
  v2_14:FireServer(v2_14)
  local v3_14 = game:GetService("ReplicatedStorage")
  v3_14 = v3_14:WaitForChild("CratesUtilities")
  v3_14 = v3_14:WaitForChild("Remotes")
  v3_14 = v3_14:WaitForChild("GiveReward")
  v3_14:FireServer(v3_14)
end

v20_1.MouseButton1Click:Connect(v23_1)
v21_1 = v19_1("Loop Drop INF Coins\
[Normal Mode] ❌️", 40)

local v24_1 = function()
  upval_0 = not upval_0

  if not upval_0 then
    if " ✅️" then
    else
    end
  end
  upval_1.Text = "Loop Drop INF Coins\
[Normal Mode]" .. " ❌️"

  if not upval_0 then

    local v2_4 = function()
      while true do
        if not upval_0 then
          if not upval_1.Parent then
            local v1_5 = game:GetService("ReplicatedStorage")
            v1_5 = v1_5:WaitForChild("Donate_Money_Remotes")
            v1_5 = v1_5:WaitForChild("Give")
            v1_5:FireServer(v1_5)
            task.wait(0.1)
          end
        end
      end
    end

    local v1_4 = task.spawn(v2_4)
    upval_2.loop1 = v1_4

  else
    if not upval_2.loop1 then
      task.cancel(upval_2.loop1)
    end
  end
end

v21_1.MouseButton1Click:Connect(v24_1)
local v22_1 = v19_1("Loop Drop INF Coins\
[SUPER FAST Mode] ❌️", 75)

local v25_1 = function()
  upval_0 = not upval_0

  if not upval_0 then
    if " ✅️" then
    else
    end
  end
  upval_1.Text = "Loop Drop INF Coins\
[SUPER FAST Mode]" .. " ❌️"

  if not upval_0 then

    local v2_7 = function()
      while true do
        if not upval_0 then
          if not upval_1.Parent then

            for v4_8 = 1, 3, 1 do
              local v5_8 = game:GetService("ReplicatedStorage")
              v5_8 = v5_8:WaitForChild("Donate_Money_Remotes")
              v5_8 = v5_8:WaitForChild("Give")
              v5_8:FireServer(v5_8)
            end
            task.wait()
          end
        end
      end
    end

    local v1_7 = task.spawn(v2_7)
    upval_2.loop2 = v1_7

  else
    if not upval_2.loop2 then
      task.cancel(upval_2.loop2)
    end
  end
end

v22_1.MouseButton1Click:Connect(v25_1)
v23_1 = v19_1("Drop 1 INF Coin", 110)

local v26_1 = function()
  local v1_9 = game:GetService("ReplicatedStorage")
  v1_9 = v1_9:WaitForChild("Donate_Money_Remotes")
  v1_9 = v1_9:WaitForChild("Give")
  v1_9:FireServer(v1_9)
end

v23_1.MouseButton1Click:Connect(v26_1)
v24_1 = v19_1("Drop INF Coins to Everyone", 145)

local v27_1 = function()
  local v0_3 = game:GetService("ReplicatedStorage")
  v0_3 = v0_3:WaitForChild("Donate_Money_Remotes")
  v0_3 = v0_3:WaitForChild("Give")
  local v2_3 = game:GetService("Players")
  local v1_3, v2_3, v3_3 = pairs(v2_3:GetPlayers())

  while true do
    if v5_3 ~= upval_0 then
      if not v5_3.Character then
        local v7_3 = v5_3.Character:FindFirstChild("HumanoidRootPart")
        if not v7_3 then
          if not upval_0.Character then
            v7_3 = upval_0.Character:FindFirstChild("HumanoidRootPart")
          end
          if not v7_3 then
            local v10_3 = Vector3.new(2, 0, 0)
            v7_3.CFrame = v5_3.Character.HumanoidRootPart.CFrame + v10_3
            v0_3:FireServer(999000000000000061374356945815914205244139101426454356548499471352657409865550443486228946667793657450670626365989097837557923453282908447796658865871354522610522300340016982631917446245752545625428043287522250366571212614037296475601070331304642881027273172123185284067548186527587667421186034027724800)
            task.wait(0.2)
            v7_3.CFrame = v7_3.CFrame
          end
        end
      end
    end

    for v4_3, v5_3 in v1_3 do
    end
end

v24_1.MouseButton1Click:Connect(v27_1)
v25_1 = Instance.new("TextBox")
v26_1 = UDim2.new(0, 120, 0, 28)
v25_1.Size = v26_1
v26_1 = UDim2.new(0, 10, 0, 208)
v25_1.Position = v26_1
v25_1.PlaceholderText = "Write Coins Value"
v25_1.Text = ""
v26_1 = Color3.fromRGB(50, 50, 50)
v25_1.BackgroundColor3 = v26_1
v26_1 = Color3.new(1, 1, 1)
v25_1.TextColor3 = v26_1
v25_1.BorderSizePixel = 0
v25_1.TextScaled = true
v25_1.Font = Enum.Font.Gotham
v26_1 = Instance.new("UICorner", v25_1)
v27_1 = UDim.new(0, 8)
v26_1.CornerRadius = v27_1
v25_1.Parent = v7_1
v26_1 = Instance.new("TextButton")
v27_1 = UDim2.new(0, 60, 0, 28)
v26_1.Size = v27_1
v27_1 = UDim2.new(0, 135, 0, 208)
v26_1.Position = v27_1
v26_1.Text = "Drop"
v26_1.Font = Enum.Font.Gotham
v26_1.TextSize = 18
v27_1 = Color3.fromRGB(40, 40, 40)
v26_1.BackgroundColor3 = v27_1
v27_1 = Color3.new(1, 1, 1)
v26_1.TextColor3 = v27_1
v26_1.BorderSizePixel = 0
v27_1 = Instance.new("UICorner", v26_1)
local v28_1 = UDim.new(0, 8)
v27_1.CornerRadius = v28_1
v26_1.Parent = v7_1

local v29_1 = function()
  local v0_16 = tonumber(upval_0.Text)

  if not v0_16 then
    if 0 < v0_16 then
      local v1_16 = game:GetService("ReplicatedStorage")
      v1_16 = v1_16:WaitForChild("Donate_Money_Remotes")
      v1_16 = v1_16:WaitForChild("Give")
      v1_16:FireServer(v0_16)
    end
  end
end

v26_1.MouseButton1Click:Connect(v29_1)

local v29_1 = function()
  local v0_10 = upval_0:IsDescendantOf(game)

  if v0_10 then
    upval_1 = false
    upval_2 = false
    local v0_10, v1_10, v2_10 = pairs(upval_3)

    while true do
      task.cancel(v4_10)

      for v3_10, v4_10 in v0_10 do
      end
    end
end

v5_1.AncestryChanged:Connect(v29_1)
v27_1 = Instance.new("TextLabel")
v28_1 = UDim2.new(1, 0, 0, 18)
v27_1.Size = v28_1
v28_1 = UDim2.new(0, 0, 1, -30)
v27_1.Position = v28_1
v27_1.BackgroundTransparency = 1
v27_1.Text = "YouTube: VylikGylik Scripts"
v28_1 = Color3.fromRGB(150, 150, 150)
v27_1.TextColor3 = v28_1
v27_1.TextTransparency = 0.1
v27_1.TextSize = 21
v27_1.Font = Enum.Font.SourceSans
v27_1.Parent = v7_1

end

end
