-- This file was generated by galactic dumper | V2.3
local fenv = getfenv()
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")
local loaded = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard", true))()
local newWindow = loaded:NewWindow('Be an SCP or Guard')
local main = newWindow:NewSection('Main')
local createToggle = main:CreateToggle('Rapid Fire', function(arg1, arg2, arg3, arg4)
    local hookfunctionResult = hookfunction(function(arg1)
        local arg1 = 0 + arg1
    end, function(arg1, arg2, arg3) --[[ Fail to get function body!! ]] end)
end)
local createToggle2 = main:CreateToggle('Hitbox SCP', function(arg1, arg2, arg3, arg4, arg5, arg6) --[[ Fail to get function body!! ]] end)
local RunService = game:GetService("RunService").RenderStepped:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local Players = game:GetService("Players"):GetPlayers()
    local HumanoidRootPart = val_2.Character:FindFirstChild('HumanoidRootPart')
end)
for i = 1, 248 do
    local Players2 = game:GetService("Players"):GetPlayers()
        local HumanoidRootPart2 = val_12.Character:FindFirstChild('HumanoidRootPart')
end
for i = 1, 252 do
        local HumanoidRootPart3 = val_507.Character:FindFirstChild('HumanoidRootPart')
end
local createToggle3 = main:CreateToggle('Hitbox MTF + Guard', function(arg1, arg2, arg3, arg4) --[[ Fail to get function body!! ]] end)
game:GetService("Players").PlayerAdded:Connect(function(arg1, arg2, arg3, arg4)
    arg1.CharacterAdded:Connect(function(arg1, arg2, arg3, arg4) --[[ Fail to get function body!! ]] end)
end)
local RunService2 = game:GetService("RunService").RenderStepped:Connect(function(arg1, arg2, arg3)
    local HumanoidRootPart4 = val_1.Character:FindFirstChild('HumanoidRootPart')
end)
for i = 1, 500 do
        local HumanoidRootPart5 = val_762.Character:FindFirstChild('HumanoidRootPart')
end
local createButton = main:CreateButton('Fly Gui', function(arg1)
    local loaded2 = loadstring(game:HttpGet("https://raw.githubusercontent.com/XNEOFF/FlyGuiV3/main/FlyGuiV3.txt", true))()
    print('HI')
end)
local newSection = newWindow:NewSection('YB@qweqrwrAX')